"""The V1→V2 cutover, asserted against the repository itself (ticket 103).

Three kinds of pin live here, deliberately outside the seam-level suites:

1. **The V1 path is gone.** `houseaccount.scoring.engine` and
   `houseaccount.scoring.weights` are deleted modules — not deprecated, not
   shimmed — and nothing under `src/` references them (R27: no side-by-side
   paths survive). `eval/golden/` and `eval/verify_claims.py` are deleted with
   them (R32); `make test-golden` over `eval/v2/golden/` is the fixture gate.

2. **The shipped `data/` run is V2-shaped.** `run_manifest.json`,
   `doors.geojson` and `houseaccount.sqlite` in the repo's real `data/` are
   regenerated by this ticket's one versioned 540-door run, so their schema is
   asserted directly (R27/R28). These tests are RED while `data/` still holds
   the V1 run — that is the point: the cutover is not done until the artifacts
   are recut.

3. **The R7 reconciliation walk.** Every published door's integer reconciles
   from its capped category subtotals, mover lift, rental modifier and
   rounding/clamp adjustment — walked over ALL published records, not a
   sample. The walk activates once the recalculated V2 run is on disk
   (skip-gated on the manifest's contract version so it cannot pass vacuously
   against V1 data).
"""

import json
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "data"
GEOJSON = DATA / "doors.geojson"
SQLITE = DATA / "houseaccount.sqlite"
MANIFEST = DATA / "run_manifest.json"

TERRITORY_TARGET = 540

#: V2 category caps (plan R2).
CAPS = {"project": 45, "capacity": 25, "fit": 48}

V1_MANIFEST_FIELDS = ("territory_median_value", "top_band_days", "doors_in_top_band")


def read_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def read_features():
    return json.loads(GEOJSON.read_text(encoding="utf-8"))["features"]


def data_run_is_v2():
    """True once the recalculated V2 artifacts are on disk."""
    if not (MANIFEST.is_file() and GEOJSON.is_file() and SQLITE.is_file()):
        return False
    return read_manifest().get("score_contract_version") == "v2"


needs_v2_run = pytest.mark.skipif(
    not data_run_is_v2(),
    reason="activates after this ticket's V2 recalculation run regenerates data/",
)


# --- 1. the V1 path is gone -----------------------------------------------------


@pytest.mark.parametrize(
    "module", ["houseaccount.scoring.engine", "houseaccount.scoring.weights"]
)
def test_the_v1_scoring_modules_are_deleted(module):
    """Deleted, not merely unused: importing must fail in a fresh interpreter
    (this process may already hold a cached module object)."""
    proc = subprocess.run(
        [sys.executable, "-c", f"import {module}"],
        capture_output=True,
        text=True,
        env={"PYTHONPATH": str(REPO / "src")},
    )
    assert proc.returncode != 0, f"{module} is still importable"
    assert "ModuleNotFoundError" in proc.stderr


def test_no_runtime_reference_to_the_v1_engine_survives_in_src():
    """R27: `grep -r` over `src/` finds no reference to the deleted modules."""
    offenders = []
    for path in sorted((REPO / "src").rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        if re.search(r"scoring\.engine|scoring\.weights|scoring import engine|scoring import weights", text):
            offenders.append(str(path.relative_to(REPO)))
    assert offenders == []


def test_the_v1_engine_and_weights_files_are_gone():
    scoring = REPO / "src" / "houseaccount" / "scoring"
    assert not (scoring / "engine.py").exists()
    assert not (scoring / "weights.py").exists()


def test_the_v1_eval_artifacts_are_deleted():
    """R32: the 13 V1 golden fixtures and the arithmetic re-implementation in
    `verify_claims.py` are deleted outright — eval/v2/golden/ is the contract."""
    assert not (REPO / "eval" / "golden").exists()
    assert not (REPO / "eval" / "verify_claims.py").exists()
    assert (REPO / "eval" / "v2" / "golden").is_dir()
    assert list((REPO / "eval" / "v2" / "golden").glob("*.json"))


def test_the_makefile_no_longer_reaches_the_deleted_eval_path():
    """`make eval` must not invoke the V1 harness over the deleted fixtures;
    `make test-golden` remains the fixture gate, over the V2 suite."""
    makefile = (REPO / "Makefile").read_text(encoding="utf-8")
    assert "verify_claims" not in makefile
    assert "eval/golden" not in makefile
    assert "eval.harness" not in makefile, "make eval still runs the V1 harness"
    assert re.search(r"^test-golden:", makefile, re.M)
    assert "tests/test_v2_golden.py" in makefile


# --- 2. the shipped data/ run is V2-shaped ---------------------------------------


def test_the_shipped_manifest_is_r28_shaped():
    payload = read_manifest()
    assert payload.get("score_contract_version") == "v2"
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", payload["as_of"])
    for field in V1_MANIFEST_FIELDS:
        assert field not in json.dumps(payload), field
    prose = json.dumps(payload.get("degradations", []))
    assert not re.search(r"90-day|could not fire|top band|top-band", prose, re.I)


def test_the_shipped_sqlite_has_the_v2_schema():
    connection = sqlite3.connect(SQLITE)
    try:
        columns = {row[1] for row in connection.execute("PRAGMA table_info(doors)")}
    finally:
        connection.close()
    assert "groups" not in columns
    assert "raw_total" not in columns
    assert {
        "score_contract_version",
        "project",
        "capacity",
        "fit",
        "base",
        "mover_strength",
        "mover_lift",
        "rental_modifier",
        "adjustment",
    } <= columns


def test_every_shipped_feature_names_the_v2_contract():
    """R27: mixed-version output is rejectable because every record says which
    contract produced it."""
    versions = {
        feature["properties"].get("score_contract_version") for feature in read_features()
    }
    assert versions == {"v2"}


# --- 3. the R7 reconciliation walk, over every published door --------------------


@needs_v2_run
def test_the_recalculated_run_covers_the_whole_territory():
    features = read_features()
    payload = read_manifest()
    assert len(features) == TERRITORY_TARGET
    assert payload["doors_total"] == TERRITORY_TARGET
    assert payload["doors_scored"] + payload["doors_unscored"] == TERRITORY_TARGET


@needs_v2_run
def test_every_published_score_reconciles_per_r7():
    """All published doors, not a sample: capped subtotals + cap adjustments
    (already inside the capped subtotals) + mover lift + rental modifier +
    rounding/clamp adjustment == the published integer."""
    walked = 0
    for feature in read_features():
        props = feature["properties"]
        if props["score"] is None:
            assert props["exclusion_reason"], props["PAMS_PIN"]
            continue
        walked += 1
        categories = props["categories"]
        assert set(categories) == set(CAPS), props["PAMS_PIN"]
        for name, cap in CAPS.items():
            assert 0 <= categories[name] <= cap, (props["PAMS_PIN"], name)
        assert sum(categories.values()) == props["base"], props["PAMS_PIN"]
        total = (
            props["base"]
            + props["mover_lift"]
            + props["rental_modifier"]
            + props["adjustment"]
        )
        assert props["score"] == pytest.approx(total, abs=1e-6), props["PAMS_PIN"]
        assert isinstance(props["score"], int) and 0 <= props["score"] <= 100
        # The evidence trail sums to the pre-rounding total (R7).
        evidence_sum = sum(item["points"] for item in props["evidence"])
        assert evidence_sum == pytest.approx(
            props["base"] + props["mover_lift"] + props["rental_modifier"], abs=1e-6
        ), props["PAMS_PIN"]
    assert walked > 0, "a walk that walked nothing proved nothing"


@needs_v2_run
def test_every_published_door_carries_the_rental_data_missing_gap():
    """R6/R23: the municipal rental registry is OPRA-only, so no live run has
    it — every scored door discloses the gap and no live door is demoted."""
    for feature in read_features():
        props = feature["properties"]
        if props["score"] is None:
            continue
        gap_types = {gap["type"] for gap in props["data_gaps"]}
        assert "rental_data_missing" in gap_types, props["PAMS_PIN"]
        assert props["rental_modifier"] == 0, props["PAMS_PIN"]


@needs_v2_run
def test_published_confidence_follows_the_r37_gap_rule():
    for feature in read_features():
        props = feature["properties"]
        if props["score"] is None:
            continue
        expected = "low" if len(props["data_gaps"]) >= 2 else "normal"
        assert props["confidence"] == expected, props["PAMS_PIN"]


@needs_v2_run
def test_the_sqlite_rows_agree_with_the_geojson():
    """One run, one truth: the two artifacts a reader can cross-check must
    carry the same integers for every door."""
    connection = sqlite3.connect(SQLITE)
    try:
        rows = {
            row[0]: row
            for row in connection.execute(
                "SELECT pams_pin, score, score_contract_version FROM doors"
            )
        }
    finally:
        connection.close()

    features = {f["properties"]["PAMS_PIN"]: f["properties"] for f in read_features()}
    assert set(rows) == set(features)
    for pin, props in features.items():
        assert rows[pin][1] == props["score"], pin
        assert rows[pin][2] == "v2", pin
