/**
 * GENERATED by web/scripts/gen-ramp-stops.mjs — do not edit.
 *
 * Interior stops are the documented quantiles of the R34 recalculation report
 * (eval/report.json score_distribution.quantiles), deduped and framed by the
 * 0 and 100 endpoints (R38). Colours are the approved prototype's blue curve
 * sampled evenly across the stops, so contrast is spent where the observed
 * distribution actually lives.
 */

/** @type {ReadonlyArray<readonly [number, number, number, number]>} [score, r, g, b] */
export const STOPS = [[0,237,239,242],[5,208,220,232],[8,175,197,220],[11,135,169,204],[13,96,139,180],[15,61,109,155],[19,39,86,134],[22,26,65,111],[100,18,47,85]];
