#!/bin/sh
# The Vercel build step: tell the static UI where the API lives (R12).
#
# `web/` has no build tooling — it is hand-written ES modules served as files —
# but it does have exactly one thing that cannot be a constant in the repo: the
# origin of the Fly.io deployment it calls. `web/js/map.js` reads
# `window.HOUSEACCOUNT_API_BASE` (defaulting to a same-origin `/api`) and
# `web/ethics.html` reads `window.HOUSEACCOUNT_ARTIFACT_BASE` (defaulting to
# `..`); on a static host neither default resolves, so the map loads no doors
# and the ethics page shows its "no published run" fallback.
#
# So this script writes those two globals into `web/js/config.js` from the
# environment and links the file from every page, at deploy time. Baking the
# origin into a committed file instead would make "point the UI at staging" a
# commit, a review and a redeploy of the repository rather than a Vercel
# environment variable.
#
# It writes into `web/` in place, which is safe because Vercel builds a throwaway
# checkout — and because both edits are idempotent, so running it locally to see
# what a deploy produces leaves a re-runnable tree.
#
# Usage: sh scripts/vercel-build.sh <api-base> <artifact-base>
#   Both may also come from HOUSEACCOUNT_API_BASE / HOUSEACCOUNT_ARTIFACT_BASE.
#   Both are required: a build that silently produced a UI pointing at nothing
#   would deploy green and fail in the browser.

set -eu

API_BASE="${1:-${HOUSEACCOUNT_API_BASE:-}}"
ARTIFACT_BASE="${2:-${HOUSEACCOUNT_ARTIFACT_BASE:-}}"

WEB_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/../web" && pwd)"
CONFIG_JS="$WEB_DIR/js/config.js"
CONFIG_TAG='<script src="js/config.js"></script>'

fail() {
  echo "vercel-build: $1" >&2
  echo "vercel-build: set HOUSEACCOUNT_API_BASE and HOUSEACCOUNT_ARTIFACT_BASE" >&2
  echo "vercel-build: (\`vercel env add\` — see docs/DEPLOY.md)" >&2
  exit 1
}

[ -n "$API_BASE" ] || fail "no API base given"
[ -n "$ARTIFACT_BASE" ] || fail "no artifact base given"

# The values are interpolated into a JavaScript string literal, so anything that
# could close it is rejected rather than escaped. These are origins; a quote or a
# backslash in one is a mistake, not a URL.
for value in "$API_BASE" "$ARTIFACT_BASE"; do
  case "$value" in
    *\"* | *\\* | *\'*) fail "quotes and backslashes are not URLs: $value" ;;
  esac
done

cat > "$CONFIG_JS" <<CONFIG
/**
 * Deploy-time configuration. Generated by scripts/vercel-build.sh — not committed.
 *
 * A classic (non-module) script, loaded from <head>, so both globals are set
 * before the deferred module scripts that read them run.
 */
window.HOUSEACCOUNT_API_BASE = "$API_BASE";
window.HOUSEACCOUNT_ARTIFACT_BASE = "$ARTIFACT_BASE";
CONFIG

# Link it from every page that has a head, unless a previous run already did.
for page in "$WEB_DIR"/*.html; do
  [ -f "$page" ] || continue
  if grep -q 'js/config\.js' "$page"; then
    continue
  fi
  awk -v tag="$CONFIG_TAG" '
    !injected && /<\/head>/ { print tag; injected = 1 }
    { print }
  ' "$page" > "$page.tmp"
  mv "$page.tmp" "$page"
done

echo "vercel-build: HOUSEACCOUNT_API_BASE=$API_BASE"
echo "vercel-build: HOUSEACCOUNT_ARTIFACT_BASE=$ARTIFACT_BASE"
echo "vercel-build: wrote ${CONFIG_JS#"$WEB_DIR/"} and linked it from web/*.html"
